/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package splashScreenz;

import java.awt.Dimension;
import java.awt.Point;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class SEARCH_ACTION_2 extends javax.swing.JFrame {

    /**
     * Creates new form SEARCH_ACTION_2
     */
    public SEARCH_ACTION_2() {
        initComponents();
         setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("tigerback.jpg")));
        this.setTitle("Student Detail");
        this.setResizable(false);
        this.setLocationRelativeTo(this);
         try{
            if(a1.length==6){   
        int x=Integer.parseInt(a1[0]);
        int y=Integer.parseInt(a1[1]);
        int w=Integer.parseInt(a1[2]);
        int h=Integer.parseInt(a1[3]);
        this.setBounds(x, y, w, h);
        }
        }catch(NullPointerException e){}
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);
        try{
            String sql="select s.NAME,s.USN,t.PROJECT,s.SEM,s.SECTION,t.MARKS,f.FACULTY,d.DEPARTMENT,s.STUDENT_MOBILE from student s join team t on t.TEAM_ID=s.TEAM_ID join department d on d.id=s.id join faculty f on t.FACULTY_ID=f.FACULTY_ID where usn=?";
            PreparedStatement ps=myconnection.getConnection().prepareStatement(sql);
            ps.setString(1,a1[4].trim());
            
            ResultSet rs=ps.executeQuery();
           // rs.next();
            if(rs.next()){
            name.setText(rs.getString(1));
            usn.setText(rs.getString(2));
            project.setText(rs.getString(3));
            sem.setText(rs.getString(4)+"  & "+rs.getString(5));
            try{marks.setText(rs.getString(6));
            
            }catch(Exception e){}
            guide.setText(rs.getString(7));
            dep.setText(rs.getString(8));
            contact.setText(rs.getString(9));
            }
            else {
            /*    String s="select * from student where usn=?";
                ps=myconnection.getConnection().prepareStatement(s);
                ps.setString(1,a1[4].trim());
               rs= ps.executeQuery();
               rs.next();
               if(rs==null)
                   JOptionPane.showMessageDialog(rootPane, "given usn not in team","",2);
                else*/
                JOptionPane.showMessageDialog(this, "USN is Not Found","",2);
            }
        }
        catch(Exception e){
        System.out.print(e);}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        menuBar1 = new java.awt.MenuBar();
        menu1 = new java.awt.Menu();
        menu2 = new java.awt.Menu();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        NAME = new javax.swing.JLabel();
        USN = new javax.swing.JLabel();
        PROJECT = new javax.swing.JLabel();
        SEM = new javax.swing.JLabel();
        MARKS = new javax.swing.JLabel();
        GUIDE = new javax.swing.JLabel();
        DEPARTMENT = new javax.swing.JLabel();
        CONTACT = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        usn = new javax.swing.JTextField();
        project = new javax.swing.JTextField();
        sem = new javax.swing.JTextField();
        guide = new javax.swing.JTextField();
        marks = new javax.swing.JTextField();
        dep = new javax.swing.JTextField();
        contact = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        jMenuItem1.setText("jMenuItem1");

        menu1.setLabel("File");
        menuBar1.add(menu1);

        menu2.setLabel("Edit");
        menuBar1.add(menu2);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("STUDENT  DETAILS");
        setAlwaysOnTop(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 255, 255));
        jLabel1.setText("NAME :");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 255, 255));
        jLabel2.setText("USN :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 70, -1));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 255, 255));
        jLabel3.setText("PROJECT TITLE :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 255, 255));
        jLabel4.setText("SEM  &  SECTION  :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 255, 255));
        jLabel5.setText("MARKS  :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 90, -1));

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 255, 255));
        jLabel6.setText("GUIDE :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 80, -1));

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("Tahoma", 3, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 255, 255));
        jLabel7.setText("DEPARTMENT :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 140, -1));

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("Tahoma", 3, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 255, 255));
        jLabel8.setText("CONTACT :");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 100, -1));

        NAME.setBackground(new java.awt.Color(0, 0, 0));
        NAME.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        NAME.setForeground(new java.awt.Color(255, 255, 0));
        jPanel1.add(NAME, new org.netbeans.lib.awtextra.AbsoluteConstraints(657, 64, 116, -1));

        USN.setBackground(new java.awt.Color(0, 0, 0));
        USN.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        USN.setForeground(new java.awt.Color(255, 255, 0));
        jPanel1.add(USN, new org.netbeans.lib.awtextra.AbsoluteConstraints(1272, 64, 188, -1));

        PROJECT.setBackground(new java.awt.Color(0, 0, 0));
        PROJECT.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        PROJECT.setForeground(new java.awt.Color(255, 255, 0));
        jPanel1.add(PROJECT, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 226, 159, -1));

        SEM.setBackground(new java.awt.Color(0, 0, 0));
        SEM.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        SEM.setForeground(new java.awt.Color(255, 255, 0));
        jPanel1.add(SEM, new org.netbeans.lib.awtextra.AbsoluteConstraints(1012, 226, 128, -1));

        MARKS.setBackground(new java.awt.Color(0, 0, 0));
        MARKS.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        MARKS.setForeground(new java.awt.Color(255, 255, 0));
        jPanel1.add(MARKS, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 369, 127, -1));

        GUIDE.setBackground(new java.awt.Color(0, 0, 0));
        GUIDE.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        GUIDE.setForeground(new java.awt.Color(255, 255, 0));
        jPanel1.add(GUIDE, new org.netbeans.lib.awtextra.AbsoluteConstraints(967, 369, 173, -1));

        DEPARTMENT.setBackground(new java.awt.Color(0, 0, 0));
        DEPARTMENT.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        DEPARTMENT.setForeground(new java.awt.Color(255, 255, 0));
        jPanel1.add(DEPARTMENT, new org.netbeans.lib.awtextra.AbsoluteConstraints(609, 631, 591, -1));

        CONTACT.setBackground(new java.awt.Color(0, 0, 0));
        CONTACT.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        CONTACT.setForeground(new java.awt.Color(255, 255, 0));
        jPanel1.add(CONTACT, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 44, -1, -1));

        name.setBackground(new java.awt.Color(204, 255, 204));
        name.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jPanel1.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 333, -1));

        usn.setBackground(new java.awt.Color(204, 255, 204));
        usn.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jPanel1.add(usn, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 333, -1));

        project.setBackground(new java.awt.Color(204, 255, 204));
        project.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jPanel1.add(project, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 333, -1));

        sem.setBackground(new java.awt.Color(204, 255, 204));
        sem.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jPanel1.add(sem, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 334, -1));

        guide.setBackground(new java.awt.Color(204, 255, 204));
        guide.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jPanel1.add(guide, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 333, -1));

        marks.setBackground(new java.awt.Color(204, 255, 204));
        marks.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jPanel1.add(marks, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 333, -1));

        dep.setBackground(new java.awt.Color(204, 255, 204));
        dep.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        dep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depActionPerformed(evt);
            }
        });
        jPanel1.add(dep, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, 333, -1));

        contact.setBackground(new java.awt.Color(204, 255, 204));
        contact.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jPanel1.add(contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 360, 333, -1));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 3, 17)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("< OK >");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 420, 139, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dragback.jpg"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 500));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void depActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_depActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     Point FormLocation;
    FormLocation=this.getLocation();
    Dimension dim1=this.getSize();
    String s[]=new String[4];
    s[0]=String.valueOf(FormLocation.x);
    s[1]=String.valueOf(FormLocation.y);
    s[2]=String.valueOf(dim1.width);
    s[3]=String.valueOf(dim1.height);
    this.dispose();
    SEARCH_ACTION.main(s);// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static String a1[]=new String[10];
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SEARCH_ACTION_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SEARCH_ACTION_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SEARCH_ACTION_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SEARCH_ACTION_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SEARCH_ACTION_2().setVisible(true);
            }
        });
         a1=args;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CONTACT;
    private javax.swing.JLabel DEPARTMENT;
    private javax.swing.JLabel GUIDE;
    private javax.swing.JLabel MARKS;
    private javax.swing.JLabel NAME;
    private javax.swing.JLabel PROJECT;
    private javax.swing.JLabel SEM;
    private javax.swing.JLabel USN;
    private javax.swing.JTextField contact;
    private javax.swing.JTextField dep;
    private javax.swing.JTextField guide;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField marks;
    private java.awt.Menu menu1;
    private java.awt.Menu menu2;
    private java.awt.MenuBar menuBar1;
    private javax.swing.JTextField name;
    private javax.swing.JTextField project;
    private javax.swing.JTextField sem;
    private javax.swing.JTextField usn;
    // End of variables declaration//GEN-END:variables
}
