/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package splashScreenz;

import java.awt.Dimension;
import java.awt.Point;
import java.awt.Toolkit;

/**
 *
 * @author user
 */
public class student_button extends javax.swing.JFrame {

    /**
     * Creates new form student_button
     */
    public student_button() {
        initComponents();this.setResizable(false);
        this.setLocationRelativeTo(this);
        System.out.print("length "+a1.length);
         try{
            if(a1.length==6){   
        int x=Integer.parseInt(a1[0]);
        int y=Integer.parseInt(a1[1]);
        int w=Integer.parseInt(a1[2]);
        int h=Integer.parseInt(a1[3]);
        this.setBounds(x, y, w, h);
        }
        }catch(NullPointerException e){}
        //.....this.setSize(600, 500);
         setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("tigerback.jpg")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jDesktopPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jDesktopPane1.setName("STUDENT FORM"); // NOI18N

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBox1.setBackground(new java.awt.Color(255, 204, 204));
        jComboBox1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(51, 51, 51));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "COMPUTER SCIENCE AND ENGINEERING", "INFORMATION SCIENCE AND ENGINEERING", "MECHANICAL ENGINEERING", "ELECTRICAL ENGINEERING", "MARINE ENGINEERING", "ELECTRONICS ENGINEERING", "OTHERS" }));
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, -1, -1));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 51));
        jLabel1.setText("SELECT DEPARTMENT :");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 153));
        jLabel2.setText("SELECT SEM :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, -1, -1));

        jComboBox2.setBackground(new java.awt.Color(255, 255, 153));
        jComboBox2.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        jPanel1.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 102));
        jLabel3.setText("SELECT SECTION :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, -1, -1));

        jComboBox3.setBackground(new java.awt.Color(255, 255, 153));
        jComboBox3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "C", "D", "E" }));
        jPanel1.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, 50, 30));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("< CANCEL >");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, 130, -1));

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("< SUBMIT >");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 350, 120, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dragback.jpg"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 610, 500));

        jDesktopPane1.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-5, -1, 610, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(inform==1){
            str[0]=(String) jComboBox1.getSelectedItem();
            str[1]=(String) jComboBox2.getSelectedItem();
            str[2]=(String) jComboBox3.getSelectedItem();
            DEFAULT_STUDENT.main(str);
        }
        else if(inform==2){
            str[4]=(String) jComboBox1.getSelectedItem();
            str[5]=(String) jComboBox2.getSelectedItem();
            str[6]=(String) jComboBox3.getSelectedItem();
               Point FormLocation;
    FormLocation=this.getLocation();
    Dimension dim1=this.getSize();
    //String s[]=new String[10];
    str[0]=String.valueOf(FormLocation.x);
    str[1]=String.valueOf(FormLocation.y);
    str[2]=String.valueOf(dim1.width);
    str[3]=String.valueOf(dim1.height);
    this.dispose();
            
            STUDENT_DEPARTMENT_NEXT.main(str);

        }
        else if(inform==3){
           str[4]=(String) jComboBox1.getSelectedItem();
            str[5]=(String) jComboBox2.getSelectedItem();
            str[6]=(String) jComboBox3.getSelectedItem();
               Point FormLocation;
    FormLocation=this.getLocation();
    Dimension dim1=this.getSize();
    //String s[]=new String[10];
    str[0]=String.valueOf(FormLocation.x);
    str[1]=String.valueOf(FormLocation.y);
    str[2]=String.valueOf(dim1.width);
    str[3]=String.valueOf(dim1.height);
    
            NOTIFICATION_ACTION.main(str);
        }
        else if(inform==4){
            str[0]=(String) jComboBox1.getSelectedItem();
            str[1]=(String) jComboBox2.getSelectedItem();
            str[2]=(String) jComboBox3.getSelectedItem();

            DEFAULT_TEAM.main(str);
        }
        else if(inform==5){

             str[4]=(String) jComboBox1.getSelectedItem();
            str[5]=(String) jComboBox2.getSelectedItem();
            str[6]=(String) jComboBox3.getSelectedItem();
               Point FormLocation;
    FormLocation=this.getLocation();
    Dimension dim1=this.getSize();
    //String s[]=new String[10];
    str[0]=String.valueOf(FormLocation.x);
    str[1]=String.valueOf(FormLocation.y);
    str[2]=String.valueOf(dim1.width);
    str[3]=String.valueOf(dim1.height);
    this.dispose();
            UPDATE_SUBMISSION.main(str);
        }
        else if(inform==6){
            str[4]=(String) jComboBox1.getSelectedItem();
            str[5]=(String) jComboBox2.getSelectedItem();
            str[6]=(String) jComboBox3.getSelectedItem();
               Point FormLocation;
    FormLocation=this.getLocation();
    Dimension dim1=this.getSize();
    //String s[]=new String[10];
    str[0]=String.valueOf(FormLocation.x);
    str[1]=String.valueOf(FormLocation.y);
    str[2]=String.valueOf(dim1.width);
    str[3]=String.valueOf(dim1.height);
    this.dispose();
            

            delete_student.main(str);
        }
        else if(inform==7){
            str[4]=(String) jComboBox1.getSelectedItem();
            str[5]=(String) jComboBox2.getSelectedItem();
            str[6]=(String) jComboBox3.getSelectedItem();
             Point FormLocation;
    FormLocation=this.getLocation();
    Dimension dim1=this.getSize();
    //String s[]=new String[10];
    str[0]=String.valueOf(FormLocation.x);
    str[1]=String.valueOf(FormLocation.y);
    str[2]=String.valueOf(dim1.width);
    str[3]=String.valueOf(dim1.height);
    this.dispose();

            TEAM_CREATION.main(str);
        }
        else if(inform==8){
             str[4]=(String) jComboBox1.getSelectedItem();
            str[5]=(String) jComboBox2.getSelectedItem();
            str[6]=(String) jComboBox3.getSelectedItem();
             Point FormLocation;
    FormLocation=this.getLocation();
    Dimension dim1=this.getSize();
    //String s[]=new String[10];
    str[0]=String.valueOf(FormLocation.x);
    str[1]=String.valueOf(FormLocation.y);
    str[2]=String.valueOf(dim1.width);
    str[3]=String.valueOf(dim1.height);
    this.dispose();
            DELETE_TEAM.main(str);
        }
        // STUDENT_DEPARTMENT_NEXT obj=new STUDENT_DEPARTMENT_NEXT();
        //  obj.setVisible(true);
        //   this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
        if(inform==1||inform==4){
            Point FormLocation;
    FormLocation=this.getLocation();
    Dimension dim1=this.getSize();
    String s[]=new String[4];
    s[0]=String.valueOf(FormLocation.x);
    s[1]=String.valueOf(FormLocation.y);
    s[2]=String.valueOf(dim1.width);
    s[3]=String.valueOf(dim1.height);
    this.dispose();
            INFORMATION.main(s);}
        else if(inform==3){ 
             Point FormLocation;
    FormLocation=this.getLocation();
    Dimension dim1=this.getSize();
    String s[]=new String[4];
    s[0]=String.valueOf(FormLocation.x);
    s[1]=String.valueOf(FormLocation.y);
    s[2]=String.valueOf(dim1.width);
    s[3]=String.valueOf(dim1.height);
    this.dispose();
            STARTING_MENU.main(s);}

        else if(inform==2||inform==5||inform==7||inform==6||inform==8){
            ;
              Point FormLocation;
    FormLocation=this.getLocation();
    Dimension dim1=this.getSize();
    String s[]=new String[4];
    s[0]=String.valueOf(FormLocation.x);
    s[1]=String.valueOf(FormLocation.y);
    s[2]=String.valueOf(dim1.width);
    s[3]=String.valueOf(dim1.height);
    this.dispose();
    EDIT_ACTION.main(s);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    String str[]=new String[10];
     public static String a1[]=new String[10];
    public static int inform=0;
    public static void main(String args[]) {
        a1=args;
       if(a1[4].equals("information"))
                inform=1;
       else if(a1[4].equals("edit")) inform=2;
       else if(a1[4].equals("notification")) inform=3;
       else if(a1[4].equals("teaminformation")) inform=4;
       else if(a1[4].equals("update")) inform=5;
       else if(a1[4].equals("deletes")) inform=6;
       else if(a1[4].equals("create")) inform=7;
       else if(a1[4].equals("deletes1")) inform=8;
       /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
       
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(student_button.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(student_button.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(student_button.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(student_button.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new student_button().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
